version: v0.1
name: create_dataset_pipeline

dataset_task:
  num_workers: 10
  batch_size: 200
  question_upper_bound: 0.8
  prefix_upper_bound: 0.85
  answer_lower_bound: 0.55
  answer_upper_bound: 0.95
  max_context_length: 1500
  max_num_context: 1
  verbose: False
  data_columns_name:
    question_name: "Nội dung câu hỏi"
    right_answer_name: "Đáp án đúng"
    options_prefix: "Đáp án "

summary_task:
  max_context_length: 1000
  rate_cluster: 0.6
  threshold: 0.7
  verbose: False

bm25_top_k: 1

convert_mapping:
  {
    "Tô - ku - ga - oa": "Tô-ku-ga-oa",
    "Si - mô - đa": "Si-mô-đa",
    "Ha - kô - đa - tê": "Ha-kô-đa-tê",
    "Mít - xưi": "Mít-xưi",
    "Mít - su - bi - si": "Mít-su-bi-si",
    "Ca - tai - a - ma": "Ca-tai-a-ma",
    "Tô - ki - ô": "Tô-ki-ô",
    "Bom - bay": "Bom-bay",
    "Mi - rút": "Mi-rút",
    "Đê - li": "Đê-li",
    "Ti - lắc": "Ti-lắc",
    "Gan - đa - kha": "Gan-đa-kha",
    "Ben - gan": "Ben-gan",
    "Can - cút - ta": "Can-cút-ta",
    "I - ta - li - a": "I-ta-li-a",
    "Hô - nô - lu - lu": "Hô-nô-lu-lu",
    "Ha - oai": "Ha-oai",
    "In - đô - nê - xi - a": "In-đô-nê-xi-a",
    "Phi - líp - pin": "Phi-líp-pin",
    "Mi - an - ma": "Mi-an-ma",
    "Ma - lai - xi - a": "Ma-lai-xi-a",
    "Xin - ga - po": "Xin-ga-po",
    "Cam - pu - chia": "Cam-pu-chia",
    "Ra - ma": "Ra-ma",
    "Đi - pô - nê - gô - rô": "Đi-pô-nê-gô-rô",
    "A - chê": "A-chê",
    "Xu - ma - tơ - ra": "Xu-ma-tơ-ra",
    "Ca - li - man - tan": "Ca-li-man-tan",
    "Sa - min": "Sa-min",
    "Min - đa - nao": "Min-đa-nao",
    "Ca - vi - tô": "Ca-vi-tô",
    "Hô - xê": "Hô-xê",
    "Ri - dan": "Ri-dan",
    "Bô - ni - pha - xi - ô": "Bô-ni-pha-xi-ô",
    "A - ghi - nan - đô": "A-ghi-nan-đô",
    "Ma - ni - la": "Ma-ni-la",
    "Nô - rô - đôm": "Nô-rô-đôm",
    "Si - vô - tha": "Si-vô-tha",
    "U - đông": "U-đông",
    "A - cha": "A-cha",
    "Cam - pốt": "Cam-pốt",
    "Pu - côm - bô": "Pu-côm-bô",
    "Khơ - me": "Khơ-me",
    "Pa - man": "Pa-man",
    "Pha - bang": "Pha-bang",
    "Pha - ca - đuốc": "Pha-ca-đuốc",
    "Xa - van - na - khét": "Xa-van-na-khét",
    "Bô - lô - ven": "Bô-lô-ven",
    "Com - ma - đam": "Com-ma-đam",
    "Mông - kút": "Mông-kút",
    "Chu - la - long - con": "Chu-la-long-con",
    "An - giê - ri": "An-giê-ri",
    "Xu - đăng": "Xu-đăng",
    "Ê - ti - ô - pi - a": "Ê-ti-ô-pi-a",
    "Ha - i - ti": "Ha-i-ti",
    "Mê - hi - cô": "Mê-hi-cô",
    "Ác - hen - ti - na": "Ác-hen-ti-na",
    "Ni - giê - ri - a": "Ni-giê-ri-a",
    "Gam - bi - a": "Gam-bi-a",
    "Kê - ni - a": "Kê-ni-a",
    "U - gan - đa": "U-gan-đa",
    "Xô - ma - li": "Xô-ma-li",
    "Ma - đa - ga - xca": "Ma-đa-ga-xca",
    "Tuy - ni - di": "Tuy-ni-di",
    "Xa - ha - ra": "Xa-ha-ra",
    "Ca - mơ - run": "Ca-mơ-run",
    "Tô - gô": "Tô-gô",
    "Tan - da - ni - a": "Tan-da-ni-a",
    "Công - gô": "Công-gô",
    "Mô - dăm - bích": "Mô-dăm-bích",
    "Ăng - gô - la": "Ăng-gô-la",
    "Ghi - nê": "Ghi-nê",
    "Áp - đen": "Áp-đen",
    "Ca - đe": "Ca-đe",
    "Át - mét": "Át-mét",
    "A - ra - bi": "A-ra-bi",
    "Mu - ha - mét": "Mu-ha-mét",
    "A - dua": "A-dua",
    "Li - bê - ri - a": "Li-bê-ri-a",
    "Ca - ri - bê": "Ca-ri-bê",
    "Tút - xanh": "Tút-xanh",
    "Lu - véc - tuy - a": "Lu-véc-tuy-a",
    "Pê - ru": "Pê-ru",
    "Guy - a - na": "Guy-a-na",
    "Cu - ba": "Cu-ba",
    "Pu - éc - tô": "Pu-éc-tô",
    "Ri - cô": "Ri-cô",
    "Ăng - ti": "Ăng-ti",
    "Mơn - rô": "Mơn-rô",
    "Oa - sinh - tơn": "Oa-sinh-tơn",
    "Pa - na - ma": "Pa-na-ma",
    "Đô - mi - ni - ca - na": "Đô-mi-ni-ca-na",
    "Ni - ca - ra - goa": "Ni-ca-ra-goa",
    "Hôn - đu - rát": "Hôn-đu-rát",
    "Bô - ơ": "Bô-ơ",
    "Xa - kha - lin": "Xa-kha-lin",
    "Ban - căng": "Ban-căng",
    "Xéc - bi": "Xéc-bi",
    "Bô - xni - a": "Bô-xni-a",
    "Pa - ri": "Pa-ri",
    "Mác - nơ": "Mác-nơ",
    "Đơ - nhi - ép": "Đơ-nhi-ép",
    "Ri - ga": "Ri-ga",
    "Véc - đoong": "Véc-đoong",
    "Lê - nin": "Lê-nin",
    "Mi - hi - en": "Mi-hi-en",
    "Bun - ga - ri": "Bun-ga-ri",
    "Vin - hem": "Vin-hem",
    "Coóc - nây": "Coóc-nây",
    "Phông - ten": "Phông-ten",
    "Mô - li - e": "Mô-li-e",
    "Bét - tô - ven": "Bét-tô-ven",
    "Mô - da": "Mô-da",
    "Rem - bran": "Rem-bran",
    "Mông - te - xki - ơ": "Mông-te-xki-ơ",
    "Vôn - te": "Vôn-te",
    "Rút - xô": "Rút-xô",
    "Mê - li - ê": "Mê-li-ê",
    "Đi - đơ - rô": "Đi-đơ-rô",
    "Vích - to": "Vích-to",
    "Huy - gô": "Huy-gô",
    "Tôn - xtôi": "Tôn-xtôi",
    "An - na": "An-na",
    "Ka - rê - ni - na": "Ka-rê-ni-na",
    "I - nô - xăng": "I-nô-xăng",
    "Xoay - ơ": "Xoay-ơ",
    "Pu - skin": "Pu-skin",
    "Ban - dắc": "Ban-dắc",
    "An - đéc - xen": "An-đéc-xen",
    "Mô - pát - xăng": "Mô-pát-xăng",
    "Se - khốp": "Se-khốp",
    "Lơn - đơn": "Lơn-đơn",
    "Béc - tơn": "Béc-tơn",
    "Ra - bin - đra - nát": "Ra-bin-đra-nát",
    "Ta - go": "Ta-go",
    "Mác - ti": "Mác-ti",
    "Phu - gi - ta": "Phu-gi-ta",
    "Pi - cát - xô": "Pi-cát-xô",
    "Lê - vi - tan": "Lê-vi-tan",
    "Trai - cốp - xki": "Trai-cốp-xki",
    "Xi - mông": "Xi-mông",
    "Phu - ri - ê": "Phu-ri-ê",
    "Ô - oen": "Ô-oen",
    "Hê - ghen": "Hê-ghen",
    "Phoi - ơ - bách": "Phoi-ơ-bách",
    "Ri - các - đô": "Ri-các-đô",
    "Ăng - ghen": "Ăng-ghen",
    "Ni - cô - lai": "Ni-cô-lai",
    "Pê - tơ - rô - grát": "Pê-tơ-rô-grát",
    "Pê - téc - bua": "Pê-téc-bua",
    "Kê - ren - xki": "Kê-ren-xki",
    "Mát - xcơ - va": "Mát-xcơ-va",
    "Xmô - nưi": "Xmô-nưi",
    "U - crai - na": "U-crai-na",
    "Bê - lô - rút - xi - a": "Bê-lô-rút-xi-a",
    "Cáp - ca - dơ": "Cáp-ca-dơ",
    "Xta - lin": "Xta-lin",
    "Hung - ga - ri": "Hung-ga-ri",
    "Ba - vi - e": "Ba-vi-e",
    "Lê - ông": "Lê-ông",
    "Bơ - lum": "Bơ-lum",
    "Phran - cô": "Phran-cô",
    "Vai - ma": "Vai-ma",
    "Hăm - buốc": "Hăm-buốc",
    "Hít - le": "Hít-le",
    "Hin - đen - bua": "Hin-đen-bua",
    "Ru - dơ - ven": "Ru-dơ-ven",
    "Cô - bê": "Cô-bê",
    "Na - gôi - a": "Na-gôi-a",
    "Ô - xa - ca": "Ô-xa-ca",
    "Ta - na - ca": "Ta-na-ca",
    "Ma - hát - ma": "Ma-hát-ma",
    "Gan - đi": "Gan-đi",
    "Gia - va": "Gia-va",
    "Ác - mét": "Ác-mét",
    "Xu - các - nô": "Xu-các-nô",
    "Su - ra - bay - a": "Su-ra-bay-a",
    "Pa - chay": "Pa-chay",
    "Prây - veng": "Prây-veng",
    "Công - pông": "Công-pông",
    "Chơ - năng": "Chơ-năng",
    "Rô - lê - phan": "Rô-lê-phan",
    "Ốt - ta - ma": "Ốt-ta-ma",
    "Pri - đi": "Pri-đi",
    "Pha - nô - mi - ông": "Pha-nô-mi-ông",
    "Béc - lin": "Béc-lin",
    "Rô - ma": "Rô-ma",
    "Xuy - đét": "Xuy-đét",
    "Xuy - dét": "Xuy-dét",
    "Muy - ních": "Muy-ních",
    "Lúc - xăm - bua": "Lúc-xăm-bua",
    "Pê - tanh": "Pê-tanh",
    "Ru - ma - ni": "Ru-ma-ni",
    "Lê - nin - grát": "Lê-nin-grát",
    "Ki - ép": "Ki-ép",
    "Giu - cốp": "Giu-cốp",
    "Xta - lin - grát": "Xta-lin-grát",
    "Von - ga - grát": "Von-ga-grát",
    "A - la - men": "A-la-men",
    "Pao - lút": "Pao-lút",
    "Cuốc - xcơ": "Cuốc-xcơ",
    "Xi - xi - li - a": "Xi-xi-li-a",
    "Mút - xô - li - ni": "Mút-xô-li-ni",
    "Gu - a - đan - ca - nan": "Gu-a-đan-ca-nan",
    "Noóc - măng - đi": "Noóc-măng-đi",
    "Pa - ti": "Pa-ti",
    "I - an - ta": "I-an-ta",
    "Toóc - gâu": "Toóc-gâu",
    "En - bơ": "En-bơ",
    "Pốt - xđam": "Pốt-xđam",
    "Hi - rô - si - ma": "Hi-rô-si-ma",
    "Na - ga - xa - ki": "Na-ga-xa-ki",
    "Pi - nhô": "Pi-nhô",
    "Bê - hen": "Bê-hen",
    "Na - pô - lê - ông": "Na-pô-lê-ông",
    "Ri - gôn": "Ri-gôn",
    "Giơ - nui - y": "Giơ-nui-y",
    "Ét - pê - răng": "Ét-pê-răng",
    "Đuy - puy": "Đuy-puy",
    "Gác - ni - ê": "Gác-ni-ê",
    "Ri - vi - e": "Ri-vi-e",
    "Cuốc - bê": "Cuốc-bê",
    "Pa - tơ - nốt": "Pa-tơ-nốt",
    "Cuốc - xi": "Cuốc-xi",
    "Brít - xô": "Brít-xô",
    "Đu - me": "Đu-me",
    "An - be": "An-be",
    "Xa - rô": "Xa-rô",
    "Ba - tay": "Ba-tay",
    "Đác - lơ": "Đác-lơ",
    "Nô - en": "Nô-en",
    " - 3,6": "-3,6",
    " - 4,1": "-4,1",
    " - 0,5": "-0,5",
    " - 1,2": "-1,2",
    " - 1,8": "-1,8",
    "SALT - 1": "SALT-1",
    "A - sô - ka": "A-sô-ka",
    "Tờ - rớt": "Tờ-rớt",
    "Véc - xai": "Véc-xai",
    "Xa - ra - tô - ga": "Xa-ra-tô-ga",
    "Bôn - sê - vích": "Bôn-sê-vích",
    "Com - ma - dam": "Com-ma-dam",
    "pa - chay": "pa-chay",
    "Công - pông - chơ - năng": "Công-pông-chơ-năng",
    "Phi - lip - pin": "Phi-lip-pin",
    "Hác - măng": "Hác-măng",
    "Xi - pay": "Xi-pay",
    "l - an - ta": "l-an-ta",
    "Hin - đu": "Hin-đu",
    "Ben - ga": "Ben-ga",
    "Xi - ha - núc": "Xi-ha-núc",
    "Sếch - xpia": "Sếch-xpia",
    "Lép - tôn - xtôi": "Lép-tôn-xtôi",
    "Pu - côm - pô": "Pu-côm-pô",
    "Bô - na - pác": "Bô-na-pác",
    "A - cha - xoa": "A-cha-xoa",
    "Mác - tuên": "Mác-tuên",
    "Xta - lin - grat": "Xta-lin-grat",
    "Xa - lô - mông": "Xa-lô-mông",
    "Mít - uây": "Mít-uây",
    "Ca - rô - lin": "Ca-rô-lin",
    "Pu - éc - tô - Ri - cô": "Pu-éc-tô-Ri-cô",
    "Véc - đooong": "Véc-đooong",
    "Ri - đan": "Ri-đan",
    "Vê - nê - xu - ê - la": "Vê-nê-xu-ê-la",
    "Luân - đôn": "Luân-đôn",
    "Xanh - pê - téc - pua": "Xanh-pê-téc-pua",
    " - đơ - rít": "-đơ-rít",
    "Víc - to - Huy - gô": "Víc-to-Huy-gô",
    "Ka - rê - ni - a": "Ka-rê-ni-a",
    "Matx - cơ - va": "Matx-cơ-va",
    "Tô - kư - ga - oa": "Tô-kư-ga-oa",
    "Bru - nây": "Bru-nây",
    "A - cha - Xoa": "A-cha-Xoa",
    "Pha - ca": "Pha-ca",
    "Chậu - pa - chay": "Chậu-pa-chay",
    "Chậu - a - nụ": "Chậu-a-nụ",
    "Pô - tem - kin": "Pô-tem-kin",
    "Ô - đét - xa": "Ô-đét-xa",
    "Lít - va": "Lít-va",
    "Gup - ta": "Gup-ta",
    "Chăm - pa": "Chăm-pa",
    "Ăng - co": "Ăng-co",
    "Mô - giô - pa - hít": "Mô-giô-pa-hít",
    "In - đô - nê - xia": "In-đô-nê-xia",
    "Gooc - ba - chôp": "Gooc-ba-chôp",
    "nơ - blô": "nơ-blô",
    "I - rắc": "I-rắc",
    "Tát - xi - nhi": "Tát-xi-nhi",
    "Na - ga - sa - ki": "Na-ga-sa-ki",
    "Rơ - ve": "Rơ-ve",
    "Nich - xơn": "Nich-xơn",
    "Giơ - ne - vơ": "Giơ-ne-vơ",
    "Ních - xơn": "Ních-xơn",
    "Mac - Namara": "Mac-Namara",
    "Mac - namara": "Mac-namara",
    "Đờ - Lát": "Đờ-Lát",
    "Đờ - tát - Xi - nhi": "Đờ-tát-Xi-nhi",
    "Tu - rơ - man": "Tu-rơ-man",
    "Ken - nơ - đi": "Ken-nơ-đi",
    "Ai - xen - hao": "Ai-xen-hao",
    "Giôn - xơn": "Giôn-xơn",
    "Gian - xơn - xi - ti": "Gian-xơn-xi-ti",
    "Át - tơn - bô - rơ": "Át-tơn-bô-rơ",
    "Xê - đa - phôn": "Xê-đa-phôn",
    "Ken - nơ - di": "Ken-nơ-di",
    "Cat - xtơri": "Cat-xtơri",
    "Na - va": "Na-va",
    "boong - ke": "boong-ke",
    "la - tinh": "la-tinh",
    "Vec - xai": "Vec-xai",
    "Vác - sa - va": "Vác-sa-va",
    "La - tinh": "La-tinh",
    "Ma - rốc": "Ma-rốc",
    "Man - ta": "Man-ta",
    "Đô - li": "Đô-li",
    "Kai - phu": "Kai-phu",
    "Phu - cư - đa": "Phu-cư-đa",
    "Tan - na - ca": "Tan-na-ca",
    "Kai - pu": "Kai-pu",
    "Ko - zu - mi": "Ko-zu-mi",
    "Mac - san": "Mac-san",
    "Tru - man": "Tru-man",
    "Nen - Xơn": "Nen-Xơn",
    "Man - đê - la": "Man-đê-la",
    "nghĩaMác - Lê": "nghĩaMác-Lê",
    "Bat - tam - bang": "Bat-tam-bang",
    "Chu - la - long": "Chu-la-long",
    "Giay - a - véc - man": "Giay-a-véc-man",
    "Bra - xin": "Bra-xin",
    "Ư - gan - đa": "Ư-gan-đa",
    "Đi - rê": "Đi-rê",
    "Đa - ua": "Đa-ua",
    "Dim - rna": "Dim-rna",
    "A - đi": "A-đi",
    "A - bê - ba": "A-bê-ba",
    "Mi - sen": "Mi-sen",
    "Hi - đan - gô": "Hi-đan-gô",
    "Si - môn": "Si-môn",
    "Bô - li - va": "Bô-li-va",
    "Hi - i - ti": "Hi-i-ti",
    "Ri - co": "Ri-co",
    "I - bê - rich": "I-bê-rich",
    "Xcan - đi - na - vi": "Xcan-đi-na-vi",
    "Bet - tô - ven": "Bet-tô-ven",
    "Trai - xcốp - ki": "Trai-xcốp-ki",
    "Sô - panh": "Sô-panh",
    "Phu - gia - ta": "Phu-gia-ta",
    "Xéc - van - téc": "Xéc-van-téc",
    "Pác - tê - nông": "Pác-tê-nông",
    "Ta - giơ": "Ta-giơ",
    "Ma - han": "Ma-han",
    "Ma - đrit": "Ma-đrit",
    "Sê - khốp": "Sê-khốp",
    "Hô - xe": "Hô-xe",
    "Mác - xim": "Mác-xim",
    "Goóc - ki": "Goóc-ki",
    "A - lếch - xan - đrô - vích": "A-lếch-xan-đrô-vích",
    "Nô - vô - xi - biếc": "Nô-vô-xi-biếc",
    "Vla - đi - vô - xtốc": "Vla-đi-vô-xtốc",
    "Mát - xco - va": "Mát-xco-va",
    "Vla - đi - vô - xt": "Vla-đi-vô-xt",
    "Kha - ba - rốp": "Kha-ba-rốp",
    "Pê - to - rô - grát": "Pê-to-rô-grát",
    "U - dơ - bê - ki - xtan": "U-dơ-bê-ki-xtan",
    "Môn - đô - va": "Môn-đô-va",
    "Cáp - ca - đơ": "Cáp-ca-đơ",
    "Gu - di - a": "Gu-di-a",
    "Tuốc - mê - ni - a": "Tuốc-mê-ni-a",
    "Tát - gi - ki - xtan": "Tát-gi-ki-xtan",
    "E - xtô - ni - a": "E-xtô-ni-a",
    "Lúc - xem - bua": "Lúc-xem-bua",
    "Hen - xin - ki": "Hen-xin-ki",
    "An - giơ - lét": "An-giơ-lét",
    "Cô - pen - ha - ghen": "Cô-pen-ha-ghen",
    "Phran - xix - cô": "Phran-xix-cô",
    "Lu - ther": "Lu-ther",
    "Si - mons": "Si-mons",
    "Mao - bát - tơn": "Mao-bát-tơn",
    "Bu - so": "Bu-so",
    "Gooc - ba - chốp": "Gooc-ba-chốp",
    "Pôn - pốt": "Pôn-pốt",
    "Mổn - Ca - đa": "Mổn-Ca-đa",
    "Gran - ma": "Gran-ma",
    "La - ha - ba - na": "La-ha-ba-na",
    "Gia - cac - ta": "Gia-cac-ta",
    "Ba - li": "Ba-li",
    "Ca - na - đa": "Ca-na-đa",
    "Mác - san": "Mác-san",
    "Giơ - ne - vc": "Giơ-ne-vc",
    "Pốt - đam": "Pốt-đam",
    "Nen - xơn": "Nen-xơn",
    "Mê - hi - co": "Mê-hi-co",
    "Pu - tin": "Pu-tin",
    "En - xin": "En-xin",
    "Giooc - ba - chốp": "Giooc-ba-chốp",
    "Brê - giơ - nếp": "Brê-giơ-nếp",
    "Véc - xai - Oasinhtơn": "Véc-xai-Oasinhtơn",
    "Na - mi - bi - a": "Na-mi-bi-a",
    "Pha - rúc": "Pha-rúc",
    "Bu - sơ": "Bu-sơ",
    "My - an - ma": "My-an-ma",
    "Mô - gôn": "Mô-gôn",
    "Clin - tơn": "Clin-tơn",
    "Lin - côn": "Lin-côn",
    "Anh - xtanh": "Anh-xtanh",
    "Lô - mô - nô - xốp": "Lô-mô-nô-xốp",
    "Vac - sa - va": "Vac-sa-va",
    "SALT - 2": "SALT-2",
    "Bu - Sơ": "Bu-Sơ",
    "Xi - ri": "Xi-ri",
    "Li - băng": "Li-băng",
    "I - ran": "I-ran",
    "Ap - ga - ni - xtan": "Ap-ga-ni-xtan",
    "Pa - let - xtin": "Pa-let-xtin",
    "Mô - dăm - bich": "Mô-dăm-bich",
    "Ê - cua - đo": "Ê-cua-đo",
    "A - pac - thai": "A-pac-thai",
    "Môn - Ca - đa": "Môn-Ca-đa",
    "Ac - hen - ti - na": "Ac-hen-ti-na",
    "Tơ - ru - man": "Tơ-ru-man",
    "Táp - hác - lây": "Táp-hác-lây",
    "Ri - gân": "Ri-gân",
    "Xan - phran - xi - cô": "Xan-phran-xi-cô",
    "Dai - bát - xư": "Dai-bát-xư",
    "An - giê - ry": "An-giê-ry",
    "Ác - hen - tina": "Ác-hen-tina",
    "Mac - x - cơ - va": "Mac-x-cơ-va",
    "héc - ta": "héc-ta",
    "Lơ - cơ - léc": "Lơ-cơ-léc",
    "Ba - lô - éc": "Ba-lô-éc",
    "Đác - giăng - li - ơ": "Đác-giăng-li-ơ",
    "Phông - ten - blô": "Phông-ten-blô",
    "Phông - ten - nơ - bloo": "Phông-ten-nơ-bloo",
    "Đờ - lát - đờ": "Đờ-lát-đờ",
    "Đờ - cát - Tơ - ri": "Đờ-cát-Tơ-ri",
    "Đờ - lát": "Đờ-lát",
    "Lô - tuyt": "Lô-tuyt",
    "Sê - nô": "Sê-nô",
    "Luông - pha - băng": "Luông-pha-băng",
    "Play - cu": "Play-cu",
    "na - va": "na-va",
    "Đờ - cát - xtơ - ri": "Đờ-cát-xtơ-ri",
    "Goóc - ba - chốp": "Goóc-ba-chốp",
    "Max - trích": "Max-trích",
    "Tê - hê - ran": "Tê-hê-ran",
    "Xa - va - na - khet": "Xa-va-na-khet",
    "Mác - Lenin": "Mác-Lenin",
    "Đa - lét": "Đa-lét",
    "Ăng - go - la": "Ăng-go-la",
    "Bec - lin": "Bec-lin",
    "vec - xai": "vec-xai",
    "B - ra - xin": "B-ra-xin",
    "“": '"',
    "”": '"',
    "–": "-",
    "…": "...",
    "‘": '"',
    "’": '"',
    "¾": "3/4",
    "¼": "1/4",
    "—": "-",
    "„": '"',
    "î": "ĩ",
    "Å": "Ấ",
    "Ȧ": "Â",
    "ð": "đ",
    "Ð": "Đ",
  }