ocr_endpoint: "https://fscidemo.fschool.dev.ftech.ai/doc/inference/file?responseFormat=raw"
convert_mapping:
  {
    "<.+?>": " ",
    "&#x00028;": "(",
    "&#x02212;": "-",
    "&#x0003D;": "-",
    "&#x00029;": ")",
    "&#x0002C;": ",",
    "&#x0002E;": ",",
    "&#x003C0;": "%",
    "&nbsp;": " ",
    "km\\?": "km2",
    "\\(\\)": " ",
    ",+": ",",
    '"+': '"',
    "'.'": " ",
    "\\.\\.\\.+": "...",
    "\\(.\\)": " ",
    "&#.+?;": " ",
    "\\s+": " ",
  }
